services:
  - type: web
    name: wordpress
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: WORDPRESS_DB_HOST
        value: db.dvjymrcvmivauwetphha.supabase.co
      - key: WORDPRESS_DB_USER
        value: postgres
      - key: WORDPRESS_DB_PASSWORD
        sync: false
      - key: WORDPRESS_DB_NAME
        value: postgres
